name: 'PHPCS'
on: [pull_request]
jobs:
  phpcs:
    uses: stellarwp/github-actions/.github/workflows/phpcs.yml@phpcs-ignore-reqs
    with:
      ref: ${{ github.event.inputs.ref }}
    secrets:
      access-token: ${{ secrets.GH_BOT_TOKEN }}